
spring:
  datasource:
    username: root
    password: Liu#1531653614
    url: jdbc:mysql://localhost:3306/tt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  #type-aliases-package: com.example.hellomybatis.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
